<!DOCTYPE html>
<html lang="zh_CN">
  <head>
    <meta charset="UTF-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>准备</title>
  </head>
  <script>
    /*
    目标:进一步理解JS中的错误(Error)和错误处理
    1.错误类型
      Eror:所有错误的父类型
      ReferenceError:引用的变量不存在
      TypeError:数据类型不正确的错误
      RangeError:数据值不存在其所允许的范围中
      SyntaxError:语法错误
    2.错误处理
      捕获错误:try .. catch
      抛出错误:thrrow error
    3.错误对象
      message属性:错误相关信息
      stack属性:函数调用栈记录信息
    */

    // 1.ReferenceError引用的变量不存在(示例不存在)
    // console.log(a);
    // 2.TypeError:数据类型不正确的错误(示例无属性)
    // let b = null;
    // console.log(b.xxx);
    // 3.RangeError数据值不存在其所允许的范围中(示例递归调用)
    // function fn() {
    //   fn();
    // }
    // fn();
    // 4.SyntaxError:语法错误(示例空串)
    // const c = """"

    //错误处理
    // try {
    //   let d = null;
    //   console.log(d.xxx);
    // } catch (error) {
    //   console.log(error.message);
    //   console.log(error.stack);
    // }

    // 抛出异常
    function something() {
      if (Date.now() % 2 === 1) {
        console.log('可以执行任务');
      } else {
        throw new Error('当前为偶数,抛出异常');
      }
    }
    try {
      something();
    } catch (error) {
      console.log(error.message);
      console.log(error.stack);
      alert(error.message);
    }
  </script>
  <body></body>
</html>
